Wdog feed during decompression process
arduino-libraries/Arduino_Portenta_OTA pull request #10
Opened 2021-06-10 20:55 UTC by pennam

This pr add the possibility to configure the watchdog feed function through API and trigger the watchdog during decompression process.

2021-06-11 06:31 UTC, aentinger requested changes

2021-06-11 12:22 UTC, pennam commented on src/Arduino_Portenta_OTA.h
> +typedef void* (*voidPrtFuncPtr)(void);
fixed with https://github.com/arduino-libraries/Arduino_Portenta_OTA/pull/10/commits/3b17dbe99b4c707af8b973f53c43f13d0d1b603b

2021-06-11 12:22 UTC, pennam commented on src/Arduino_Portenta_OTA.h
> +#define PORTENTA_OTA_HAS_WATCHDOG_FEED
fixed with https://github.com/arduino-libraries/Arduino_Portenta_OTA/pull/10/commits/14b763848c61f023884bdc019b798fa25ac93770

2021-06-14 12:56 UTC, aentinger approved these changes

2021-06-14 12:56 UTC, merged