OTA download and decompress on the fly
arduino-libraries/Arduino_Portenta_OTA pull request #43
Opened 2023-12-05 13:47 UTC by andreagilardoni

This PR aims to provide a easy to use utility class `LZSSDecoder` that can be used to perform an OTA update on the fly. 
Since in the mbed core we provide apis for http download using callbacks it was required to adapt the code for the decode function.

Some examples for the usage of `LZSSDecoder` were added and they made it possible to measure the performance improvements obtained from a sequential download and decompress to a download and decompress on the fly:
```
Starting download to QSPI ...
819600 bytes stored.

download elapsed 31.07s speed: 25.76KBps
decompress elapsed 82.13s size 1048576

Starting download & decompress on the fly
downloaded 819600 bytes 1048576 bytes stored.
download elapsed 39.27s speed: 20.38KBps
```

This way the OTA download and decompress operations now take 35% of the time

2023-12-05 13:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/arduino-libraries/Arduino_Portenta_OTA?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/arduino-libraries/Arduino_Portenta_OTA?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/arduino-libraries/Arduino_Portenta_OTA?pullRequest=43) it.</sub>

2024-01-16 09:03 UTC, pennam requested changes
@andreagilardoni i've tested the code and it works.  Just a couple of minor things that i think can be improved:

 - commit history can be improved a little bit more. All subsequentials changes to the LZSSDecoder can be squashed in a single commit.
 - Alway put a space after `if`  `for` ... to be consistent to the code style

2024-01-16 09:03 UTC, pennam commented on src/decompress/utility.cpp
> +    uint32_t header_copied_bytes=0;
Add spaces around `=` to maintain codestyle

2024-01-16 12:28 UTC, andreagilardoni commented on src/decompress/utility.cpp
> +    for(char* cursor=(char*)buffer; cursor<buffer+size; ) {
The correct approach will be to define buffer as `char* const`, but this requires lots of changes in the core code. Then cast cursor to `uint8_t*` in decompress call

2024-01-16 14:31 UTC, pennam commented on src/decompress/lzss.h
> +    } state;
@andreagilardoni i would give a more meaningful name to this FSM states if it possible

2024-02-05 15:04 UTC, andreagilardoni commented on src/decompress/lzss.h
> +    } state;
There are no meaningful names for those states

2024-02-05 15:14 UTC, pennam commented
@andreagilardoni CI is failing because is using an old deprecated mbed core for portenta. See https://github.com/arduino-libraries/Arduino_Portenta_OTA/blob/49f839aa75c9359e8ec85016b21b2b04ad175e68/.github/workflows/compile-examples.yml#L37

2024-02-13 09:45 UTC, merged